### ISSUE TITLE
googler snap app (ver 3.7.1) - browser integration issue

### ISSUE THREAD

**Issue by timeislove** [snapcrafters/googler#5]
hello,

tried the snap app (V3.7.1). the latest snap is promoted to 3.8 from the previous edge channel but exhibited "Connection blocked due to unusual activity" issue. (ticket raised - https://github.com/jarun/googler/issues/276)

after inputting the search result index, the app was **not** able to trigger gui default browser,  **nor** other text browser even if overridden by env setting BROWSER=.

as a comparison, the snap app ddgr (ver 1.6) from the same develop *was* able to trigger the default browser though still not functioning with BROWSER= setting.

running snapd (2.38+) on xubuntu 18.04.2

regards

here below the debug log:

$ googler -d --show-browser-logs obama
[DEBUG] googler version 3.7.1
[DEBUG] Python version 3.5.2
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=obama
[DEBUG] Cookie: 1P_JAR=2019-04-06-13
[DEBUG] Response body written to '/tmp/googler-response-jpjs6ohh'.

1 Barack Obama - Wikipedia
https://en.wikipedia.org/wiki/Barack_Obama
Barack Hussein Obama II is an American attorney and politician who served as the 44th president of the United States from 2009 to 2017. A
member of the ...

2 The Office of Barack and Michelle Obama
https://barackobama.com/
Welcome to the Office of Barack and Michelle Obama. We Love You Back. Play video. The Office of Barack and Michelle Obama · Obama Foundation.
obama.

3 Barack Obama (@BarackObama) | Twitter
https://twitter.com/barackobama
The latest Tweets from Barack Obama (@BarackObama). Dad, husband, President, citizen. Washington, DC.

4 Barack Obama - Home | Facebook
https://www.facebook.com/barackobama/
Barack Obama, Washington, DC. 54M likes. Dad, husband, former President, citizen.

5 Barack Obama | Biography, Presidency, & Facts | Britannica.com
https://www.britannica.com/biography/Barack-Obama
15 Mar 2019 ... did you know? When Obama traveled to Kenya in 2006, thousands of people waited to welcome him, lining the streets. The Obamas
signed a ...

6 Welcome to the Obama Foundation
https://www.obama.org/
"I'm asking you to believe. Not in my ability to create change — but in yours." President Barack Obama.

7 Barack Obama - HISTORY
https://www.history.com/topics/us-presidents/barack-obama
On November 4, 2008, Senator Barack Obama of Illinois was elected president of the United States over Senator John McCain of Arizona. Obama
became the ...

8 Barack Obama | Miller Center
https://millercenter.org/president/obama
Barack Obama was inaugurated as the 44th president of the United States—becoming the first African American to serve in that office—on January
20, 2009.

9 Entrenching the Obama Presidency - WSJ
https://www.wsj.com/articles/entrenching-the-obama-presidency-11554506803
14 hours ago ... A federal judge rules that Trump can't revoke Obama's oil drilling ban.

10 Barack Obama - The New York Times
http://www.nytimes.com/topic/person/barack-obama
News about Barack Obama. Commentary and archival information about Barack Obama from The New York Times.

googler (? for help) 6
[DEBUG] Opening https://www.obama.org/
googler (? for help) O 6
[DEBUG] Opening https://www.obama.org/
[DEBUG] <webbrowser.BackgroundBrowser object at 0x7f9d2dd2bb38>
googler (? for help) q

**Comment by lucyllewy** [comment]
I've uploaded a fixed version. It is released now, so you should get it automatically shortly, or you can force it to update by running `sudo snap refresh googler` in a terminal.
