### ISSUE TITLE
Googler not returning results

### ISSUE THREAD

**Issue by aplatypus** [snapcrafters/googler#8]
Bug reports
problem

Snap installed version for Googler fails on Ubuntu 19.04 command line with a permissions error.

```
 $  googler -d microsoft
2019/12/18 11:43:21.698430 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/william/snap: exec: "matchpathcon": executable file not found in $PATH
2019/12/18 11:43:21.698488 cmd_run.go:529: WARNING: XAUTHORITY environment value is not a clean path: "/data/home/william/.Xauthority"
cannot create user data directory: /home/william/snap/googler/457: Not a directory
```
I can't really tell you what version has the problem because as you see ...
```
 $ googler --version
2020/01/06 08:18:05.162006 cmd_run.go:884: WARNING: cannot create user data directory: failed to verify SELinux context of /home/william/snap: exec: "matchpathcon": executable file not found in $PATH
2020/01/06 08:18:05.162250 cmd_run.go:529: WARNING: XAUTHORITY environment value is not a clean path: "/data/home/william/.Xauthority"
cannot create user data directory: /home/william/snap/googler/457: Not a directory
```

The `snap` utility reports that this is the version that's supposed to be installed:
```
 $ snap list  googler
Name     Version  Rev  Tracking  Publisher     Notes
googler  4.0      457  stable    snapcrafters  -

 $ snap --version
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  19.04
kernel  5.0.7-050007-generi
```

I hope snaps can resolve these permission errors.  There is an ever increasing list of apps that don't run for one or more reason(s) that just don't run because of permissions.  I run the same level of Ubuntu and updates on two machines, and these issues are common to both.  It just seems like something fundemental to the snap model is wonky.

see:  
  - [313 -- Googler not returning results](https://github.com/jarun/googler/issues/313)
  - [5 -- googler snap app (ver 3.7.1) - browser integration issue](https://github.com/snapcrafters/googler/issues/5)
    - Looks similar but this is for completely different releases
    - Either this is a different bug, or it is a regression error.

Thanks in advance,

aplatypus

**Comment by popey** [comment]
Thanks for the bug report. I have tested the snap and it works fine here. I note from the error it's having trouble making a directory `/home/william/snap/googler/457`. This suggests perhaps your home directory is non-standard? How is `/home/william/` mounted?
